title: Sluit een zoemer aan
hero_image: images/banner.png
description: Hoe kun je een zoemer aansluiten op een Raspberry Pi Pico
version: 4
listed: false
copyedit: false
last_tested: "2022-02-15"
steps:
  - 
    title: Sluit een zoemer aan
